kafka:
  bootstrap-servers: ${spring.embedded.kafka.brokers}
  group: journal
  topic:
    income: journal
    outcome: journal
    failure: journal_failures
jdbc:
  driver: org.sqlite.JDBC
  url: jdbc:sqlite:${user.dir}/src/main/resources/database/emulator.db